name: Dev Builds
on:
  push:
    branches: 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out branch
        uses: actions/checkout@v3

      - name: Init submodules
        uses: snickerbockers/submodules-init@v4

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.7

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build library
        run: gradle library:assemble --stacktrace

      - name: Build developer APK
        env:
          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          RELEASE_KEYSTORE_ALIAS: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: gradle assembleRelease --stacktrace

      - name: ZipAlign & Sign Android release
        uses: kevin-david/zipalign-sign-android-release@v2.0.1
        id: sign
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE_64 }}
          alias: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.RELEASE_KEY_PASSWORD }}
          keyPassword: ${{ secrets.RELEASE_KEY_PASSWORD }}
          zipAlign: true

      - name: Rename APK
        run: cp ${{steps.sign.outputs.signedReleaseFile}} app/build/outputs/apk/release/app-release.apk

      - name: Generate MD5sum
        run: md5sum ${{steps.sign.outputs.signedReleaseFile}} > app/build/outputs/apk/release/app-release.md5

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dev-artifacts
          path: |
            app/build/outputs/apk/release/app-release.apk
            app/build/outputs/apk/release/app-release.md5
